# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version} 配置文件
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# 现在可以在配置文件和消息文件中使用以下占位符:
# - %name% - 替换为玩家名称，例如："Notch"。
# - %displayname% - 替换为玩家的显示名称，例如："[Owner] Notch"。
# - %uuid% - 替换为玩家的 UUID。
# - %crate% - 宝箱类型的名称。
# - %prize% - 奖励的名称。
# - %percentage% - 奖励的百分比，用于"概率提示"。
# - %rand;100;500% - 生成两个数字之间的随机数，示例在 100 和 500 之间。
# ------------------------------------------
# 请勿修改配置版本号！

Config Version: 7

# 插件前缀
Prefix: "&7[&bCratesPlus&7]"

# 检查是否有可用更新并通知管理员
Update Checks: true
Update Branch: "release"

# 上传匿名的服务器数据，用于统计数据
Metrics: true

Crates:

# 默认使用的开启方式
Default Opener: BasicGUI

# 打开宝箱之间的默认冷却时间
Default Cooldown: 5

# 如果为 true，将阻止没有管理员权限的玩家破坏宝箱
Crate Protection: false

# 禁止玩家将钥匙丢给其他玩家、放入箱子或在死亡时掉落
Disable Key Swapping: false

Chance Message Gap: true

# %crate% 可用于显示宝箱名称
Default Hologram Text:
- "%crate%"
- "&e右键点击打开！"
- "&e左键点击预览！"

# 使用哪种存储系统。支持 FLAT、SQLite 或 MySQL
Storage Type: FLAT

# 仅当上方设置为 MySQL 时才需要
MySQL Host: localhost
MySQL User: username
MySQL Pass: password
MySQL Database: database